package io.github.zhlzxa.corebanking.cash;

import java.math.BigDecimal;
import org.jspecify.annotations.Nullable;

/**
 * A cash deposit into, or withdrawal from, a customer account, handled by a member of staff or a
 * machine rather than by the customer directly.
 *
 * @param operatorId the user performing the operation, such as a teller, recorded as initiator;
 *     {@code null} for machines, which are not bank users
 * @param requestId idempotency key generated by the operating system at the counter or terminal
 */
public record CashCommand(
        @Nullable Long operatorId, String requestId, long accountId, BigDecimal amount, String currency) {}
