-- Purpose: transactional outbox for integration events, and consumer-side
-- deduplication.
--
-- Writing to the database and to a message broker in one step is impossible
-- without distributed transactions. Instead, an event is inserted into
-- outbox_events in the same database transaction as the business change it
-- describes, and a separate publisher delivers it to the broker afterwards.
-- Delivery is at least once; consumers deduplicate by event_id.

CREATE TABLE outbox_events (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id         UUID          NOT NULL,
    aggregate_type   VARCHAR(50)   NOT NULL,
    aggregate_id     VARCHAR(100)  NOT NULL,
    event_type       VARCHAR(100)  NOT NULL,
    payload          JSONB         NOT NULL,
    occurred_at      TIMESTAMPTZ   NOT NULL,
    published_at     TIMESTAMPTZ,
    attempt_count    INT           NOT NULL DEFAULT 0,
    next_attempt_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    last_error       VARCHAR(500),
    CONSTRAINT uq_outbox_events_event_id UNIQUE (event_id)
);

-- The publisher's work queue. Published rows are the vast majority and are
-- excluded, so the index stays small however much history accumulates.
CREATE INDEX idx_outbox_events_unpublished ON outbox_events (next_attempt_at)
    WHERE published_at IS NULL;

-- Events a consumer has already handled, recorded in the same transaction as
-- the consumer's own side effect.
CREATE TABLE processed_events (
    consumer      VARCHAR(100) NOT NULL,
    event_id      UUID         NOT NULL,
    processed_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    PRIMARY KEY (consumer, event_id)
);

-- Example consumer side effect: a notification per completed transaction and
-- affected customer account.
CREATE TABLE account_notifications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id      BIGINT       NOT NULL REFERENCES accounts (id),
    transaction_id  BIGINT       NOT NULL REFERENCES transactions (id),
    kind            VARCHAR(20)  NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_account_notifications_kind CHECK (kind IN ('MONEY_IN', 'MONEY_OUT'))
);
