-- Purpose: core double-entry ledger.
--
-- accounts        current balance per account, maintained together with the ledger
-- transactions    one row per business money movement; request_id makes it idempotent
-- ledger_entries  immutable debit/credit postings; every transaction nets to zero
--
-- Monetary columns use NUMERIC(19,4): exact decimal arithmetic with headroom
-- for currencies that have more than two minor units. The API enforces the
-- per-currency scale.

CREATE TABLE accounts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency    CHAR(3)        NOT NULL,
    balance     NUMERIC(19, 4) NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT ck_accounts_currency_iso CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_accounts_balance_non_negative CHECK (balance >= 0)
);

CREATE TABLE transactions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Client-generated idempotency key; length must match the API validation.
    request_id        VARCHAR(100)   NOT NULL,
    transaction_type  VARCHAR(20)    NOT NULL,
    status            VARCHAR(20)    NOT NULL,
    from_account_id   BIGINT         NOT NULL REFERENCES accounts (id),
    to_account_id     BIGINT         NOT NULL REFERENCES accounts (id),
    amount            NUMERIC(19, 4) NOT NULL,
    currency          CHAR(3)        NOT NULL,
    created_at        TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT uq_transactions_request_id UNIQUE (request_id),
    CONSTRAINT ck_transactions_type CHECK (transaction_type IN ('TRANSFER')),
    CONSTRAINT ck_transactions_status CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED')),
    CONSTRAINT ck_transactions_amount_positive CHECK (amount > 0),
    CONSTRAINT ck_transactions_distinct_accounts CHECK (from_account_id <> to_account_id)
);

CREATE TABLE ledger_entries (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id  BIGINT         NOT NULL REFERENCES transactions (id),
    account_id      BIGINT         NOT NULL REFERENCES accounts (id),
    direction       VARCHAR(6)     NOT NULL,
    amount          NUMERIC(19, 4) NOT NULL,
    currency        CHAR(3)        NOT NULL,
    created_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),
    -- Guards against posting the same leg twice; also indexes transaction_id.
    CONSTRAINT uq_ledger_entries_leg UNIQUE (transaction_id, account_id, direction),
    CONSTRAINT ck_ledger_entries_direction CHECK (direction IN ('DEBIT', 'CREDIT')),
    CONSTRAINT ck_ledger_entries_amount_positive CHECK (amount > 0)
);

-- Ledger entries are an accounting record: corrections are made with new,
-- offsetting entries, never by editing or deleting history.
CREATE FUNCTION reject_ledger_entry_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'ledger_entries is append-only: % is not permitted', TG_OP
        USING ERRCODE = 'insufficient_privilege';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_ledger_entries_append_only
    BEFORE UPDATE OR DELETE ON ledger_entries
    FOR EACH ROW EXECUTE FUNCTION reject_ledger_entry_mutation();
