-- Purpose: bank users and account ownership.
--
-- Authentication is delegated to an external OpenID Connect provider. A user
-- is identified by the provider's (issuer, subject) pair, which never changes
-- for a person, unlike usernames or e-mail addresses. The bank role and status
-- are owned by the bank, not by the token.

CREATE TABLE users (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identity_issuer   VARCHAR(512) NOT NULL,
    identity_subject  VARCHAR(255) NOT NULL,
    display_name      VARCHAR(100) NOT NULL,
    role              VARCHAR(20)  NOT NULL,
    status            VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_external_identity UNIQUE (identity_issuer, identity_subject),
    CONSTRAINT ck_users_role CHECK (role IN ('CUSTOMER', 'TELLER', 'ADMIN')),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'LOCKED', 'DISABLED'))
);

-- Nullable: bank-internal accounts (cash, clearing, fee income) have no owner.
ALTER TABLE accounts ADD COLUMN user_id BIGINT REFERENCES users (id);

-- The user on whose behalf the money movement was requested. Retries are only
-- recognised as retries when they come from the same user.
ALTER TABLE transactions ADD COLUMN initiated_by_user_id BIGINT REFERENCES users (id);
