-- Purpose: business audit trail.
--
-- One row per business-relevant action, successful or not: who acted (as
-- established by authentication, never by request content), what they did,
-- on which resource, with which outcome, and the correlation id that links the
-- row to application logs. Rows are immutable.
--
-- Foreign keys deliberately have no ON DELETE action: users and transactions
-- referenced by audit history can be deactivated but never deleted.

CREATE TABLE audit_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        UUID          NOT NULL,
    -- Set by the application clock; no default so that a missing value is a bug, not "now".
    occurred_at     TIMESTAMPTZ   NOT NULL,
    actor_user_id   BIGINT        REFERENCES users (id),
    actor_issuer    VARCHAR(512),
    actor_subject   VARCHAR(255),
    actor_role      VARCHAR(20),
    action          VARCHAR(100)  NOT NULL,
    resource_type   VARCHAR(100)  NOT NULL,
    resource_id     VARCHAR(255),
    transaction_id  BIGINT        REFERENCES transactions (id),
    request_id      VARCHAR(100),
    correlation_id  VARCHAR(100),
    channel         VARCHAR(20)   NOT NULL,
    outcome         VARCHAR(20)   NOT NULL,
    reason_code     VARCHAR(100),
    metadata        JSONB         NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT uq_audit_events_event_id UNIQUE (event_id),
    CONSTRAINT ck_audit_events_outcome CHECK (outcome IN ('SUCCESS', 'REJECTED', 'FAILED')),
    -- A reason is mandatory for anything that did not succeed.
    CONSTRAINT ck_audit_events_reason CHECK (outcome = 'SUCCESS' OR reason_code IS NOT NULL)
);

-- "What did this user do recently?"
CREATE INDEX idx_audit_events_actor_time ON audit_events (actor_user_id, occurred_at DESC);
-- "Show the audit trail of this transaction."
CREATE INDEX idx_audit_events_transaction ON audit_events (transaction_id);
-- "What happened to this client request?" including rejected ones without a transaction.
CREATE INDEX idx_audit_events_request_id ON audit_events (request_id);
-- "All failed logins / denied operations in a period."
CREATE INDEX idx_audit_events_action_time ON audit_events (action, occurred_at DESC);

CREATE FUNCTION reject_audit_event_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'audit_events is append-only: % is not permitted', TG_OP
        USING ERRCODE = 'insufficient_privilege';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_audit_events_append_only
    BEFORE UPDATE OR DELETE ON audit_events
    FOR EACH ROW EXECUTE FUNCTION reject_audit_event_mutation();
