-- Purpose: saved payees ("address book") of a customer.
--
-- A payee is reference data owned by one customer; it does not move money and
-- is maintained through the JPA-based payee module. See ADR-0006.

CREATE TABLE payees (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL REFERENCES users (id),
    nickname        VARCHAR(50)  NOT NULL,
    -- Up to 34 characters so that an IBAN fits.
    account_number  VARCHAR(34)  NOT NULL,
    -- Null for accounts held at this bank.
    bank_code       VARCHAR(20),
    currency        CHAR(3)      NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    -- Optimistic locking: incremented on every update by the persistence layer.
    version         BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT ck_payees_currency_iso CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_payees_nickname_not_blank CHECK (btrim(nickname) <> ''),
    -- A customer cannot save the same destination twice. NULLS NOT DISTINCT treats two
    -- entries without a bank code as equal. The leading user_id also serves the
    -- "list my payees" query, so no separate index is needed.
    CONSTRAINT uq_payees_owner_destination UNIQUE NULLS NOT DISTINCT (user_id, bank_code, account_number)
);
