-- Purpose: four-eyes approval of large cash withdrawals.
--
-- A teller (maker) requests the withdrawal; a different teller (checker) must
-- approve it before any money moves. The request expires if nobody decides in
-- time. The row keeps the full decision history: who asked, who decided, when,
-- and which transaction executed it.

CREATE TABLE withdrawal_approvals (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- The idempotency key of the withdrawal; reused as the transaction's request id.
    request_id         VARCHAR(100)   NOT NULL,
    account_id         BIGINT         NOT NULL REFERENCES accounts (id),
    amount             NUMERIC(19, 4) NOT NULL,
    currency           CHAR(3)        NOT NULL,
    maker_user_id      BIGINT         NOT NULL REFERENCES users (id),
    maker_branch_code  VARCHAR(20)    NOT NULL,
    status             VARCHAR(20)    NOT NULL DEFAULT 'PENDING',
    checker_user_id    BIGINT         REFERENCES users (id),
    decided_at         TIMESTAMPTZ,
    transaction_id     BIGINT         REFERENCES transactions (id),
    created_at         TIMESTAMPTZ    NOT NULL DEFAULT now(),
    expires_at         TIMESTAMPTZ    NOT NULL,
    CONSTRAINT uq_withdrawal_approvals_request_id UNIQUE (request_id),
    CONSTRAINT ck_withdrawal_approvals_amount_positive CHECK (amount > 0),
    CONSTRAINT ck_withdrawal_approvals_status CHECK (status IN ('PENDING', 'EXECUTED', 'REJECTED', 'EXPIRED')),
    -- The four-eyes principle, enforced by the database as well as by the service.
    CONSTRAINT ck_withdrawal_approvals_four_eyes CHECK (checker_user_id IS NULL OR checker_user_id <> maker_user_id),
    -- A decision always records who decided and when; an execution records the transaction.
    CONSTRAINT ck_withdrawal_approvals_decision CHECK (
        (status = 'PENDING' AND checker_user_id IS NULL AND decided_at IS NULL AND transaction_id IS NULL)
        OR (status = 'EXPIRED' AND checker_user_id IS NULL AND decided_at IS NOT NULL AND transaction_id IS NULL)
        OR (status = 'REJECTED' AND checker_user_id IS NOT NULL AND decided_at IS NOT NULL AND transaction_id IS NULL)
        OR (status = 'EXECUTED' AND checker_user_id IS NOT NULL AND decided_at IS NOT NULL AND transaction_id IS NOT NULL))
);

-- "Requests waiting for a decision at my branch."
CREATE INDEX idx_withdrawal_approvals_pending ON withdrawal_approvals (maker_branch_code, created_at)
    WHERE status = 'PENDING';
